CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	email CHARACTER VARYING(320) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id)
);

CREATE TABLE public.employees(
	id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	CONSTRAINT pk_employees PRIMARY KEY(id),
	CONSTRAINT fk_employees_users FOREIGN KEY(id) REFERENCES public.users(id)
);

CREATE TABLE public.individuals(
	id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	identity_number CHARACTER VARYING(11) NOT NULL,
	birth_year INT NOT NULL,
	account_number INT NOT NULL,
	cent BIGINT NOT NULL,
	CONSTRAINT pk_individuals PRIMARY KEY(id),
	CONSTRAINT fk_individuals_users FOREIGN KEY(id) REFERENCES public.users(id),
	CONSTRAINT uk_individuals_identity_number UNIQUE(identity_number)
);

CREATE TABLE public.institutionals(
	id INT NOT NULL,
	company_name CHARACTER VARYING(255) NOT NULL,
	web_address CHARACTER VARYING(50) NOT NULL,
	phone_number CHARACTER VARYING(12) NOT NULL,
	account_number INT NOT NULL,
	cent BIGINT NOT NULL,
	CONSTRAINT pk_institutionals PRIMARY KEY(id),
	CONSTRAINT fk_institutionals_users FOREIGN KEY(id) REFERENCES public.users(id)
);